---
name: Continous Deployment

on:
  push:
    branches:
      - main
      - production
  pull_request: []
jobs:
  test:
    name: Test
    run-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run -rm app.sh -c "python manage.py"
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
